<template>
    <div class="outerContainer">
      <h1>Privacy Policy</h1>

<p>The following explains what information is collected during your visit to our website and how it is used. The privacy policy applies to the online presence of the domain svenjaraetzsch.de, as well as to any web applications contained therein. Websites linked to our online presence are not included. We are available to assist you with any privacy-related concerns related to our online presence. Please direct your inquiries to the following email address: <a href="mailto:info@svenjaraetzsch.de">info@svenjaraetzsch.de</a>.</p>

<h2>Information and Deletion of Your Personal Data</h2>
<p>Upon request, you can receive information about your currently stored personal data with us. Additionally, you have the right to block and delete the data we have stored about you at any time.</p>

<h2>Personal Data</h2>
<p>You can visit our website without us collecting personal data about you. Personal data is only collected if you voluntarily provide it to us as part of contacting us. The personal data you provide will be used exclusively for the specified purpose, such as responding to your contact inquiry. We do not share, sell, or transmit your personal data to third parties.</p>

<h2>Non-Personal Data</h2>
<p>When you visit our website, automatically collected information not associated with a specific person is gathered. This information includes your computer's IP address, the internet browser used by the computer, the computer's operating system, the web pages you visit on our online presence, the date and duration of your visit, and the domain name of the website from which you came (if applicable). Our website uses applications from "Amazon Web Services" and is operated on an instance in Frankfurt. The automatically collected, anonymous information is transmitted to secure systems operated by Amazon Web Services for organizational and technical reasons. More information about Amazon Web Services and privacy at Amazon can be found at <a href="http://aws.amazon.com/en/">here</a> and <a href="https://aws.amazon.com/en/privacy/">here</a>.</p>

<h2>Cookies</h2>
<p>Websites sometimes use cookies to make offerings on web pages more user-friendly, personalized, and secure. Cookies are stored locally on your computer by your internet browser. On our websites, we use both session cookies (automatically deleted after your visit) and cookies that remain on your device until you delete them. You can block the use of cookies at any time and enable the automatic deletion of cookies at the end of your visit. This does not restrict access to our website, but certain functions or sections may no longer be available. If you have questions about blocking or deleting cookies generated by our website, feel free to contact us at <a href="mailto:info@svenjaraetzsch.de">info@svenjaraetzsch.de</a>.</p>

<h2>Google Analytics</h2>
<p>This website uses Google Analytics, a web analytics service provided by Google LLC. The responsible entity for users in the EU/EEA and Switzerland is Google Ireland Limited, Google Building Gordon House, 4 Barrow St, Dublin, D04 E5W5, Ireland ("Google").</p>

<h3>Processing Scope</h3>
<p>Google Analytics uses cookies that allow an analysis of your use of our websites. Information collected through these cookies about your use of this website is generally transmitted to and stored on a Google server in the United States. We use the User-ID function to assign a unique, permanent ID to one or more sessions (and the activities within those sessions) and to analyze user behavior across devices. We use Google Signals to capture additional information about users who have enabled personalized ads (interests and demographic data), and ads can be delivered to these users in cross-device remarketing campaigns. IP addresses are anonymized by default in Google Analytics. Due to IP anonymization, your IP address is shortened by Google within the European Union member states or in other signatory states to the Agreement on the European Economic Area. Only in exceptional cases is the full IP address transmitted to a Google server in the United States and then shortened there. According to Google, the IP address transmitted by your browser as part of Google Analytics is not merged with other Google data. Your user behavior is recorded in the form of "events" during your website visit. Events can include page views, first-time visits to the website, session start, your click path, interaction with the website, scrolls (whenever a user scrolls to the end (90%) of a page), clicks on external links, internal search queries, interaction with videos, file downloads, viewed/clicked ads, language settings, approximate location (region), IP address (in truncated form), technical information about your browser and devices used (e.g., language settings, screen resolution), your internet service provider, and the referrer URL (the website/advertisement through which you came to this website).</p>

<h3>Processing Purposes</h3>
<p>On behalf of the operator of this website, Google will use this information to evaluate your use of the website and to compile reports on website activity. The reports provided by Google Analytics are used to analyze the performance of our website.</p>

<h3>Recipients</h3>
<p>Data recipients may include Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Ireland (as a data processor according to Art. 28 GDPR), Google LLC, 1600 Amphitheatre Parkway Mountain View, CA 94043, USA, and Alphabet Inc., 1600 Amphitheatre Parkway Mountain View, CA 94043, USA. It cannot be ruled out that US authorities may access the data stored by Google.</p>

<h3>International Data Transfers</h3>
<p>To ensure an adequate level of data protection when processing data outside the EU/EEA where there is no equivalent European standard of data protection, we have entered into EU Standard Contractual Clauses with the service provider. Google Ireland's parent company, Google LLC, is based in California, USA. The transfer of data to the USA and access by US authorities to the data stored by Google cannot be ruled out. Currently, the USA is considered a third country from a data protection perspective. You do not have the same rights there as within the EU/EEA, and there may be no remedies available to you against government access.</p>

<h3>Storage Duration</h3>
<p>Data sent by us and linked with cookies are automatically deleted after 2 years. The deletion of data whose retention period has expired is automatically performed once a month.</p>

<h3>Legal Basis</h3>
<p>The legal basis for this data processing is your consent according to Art. 6 para. 1 sentence 1 lit. a GDPR.</p>

<h3>Revocation</h3>
<p>You can revoke your consent at any time with effect for the future by accessing the cookie settings and changing your selection there. The legality of processing based on consent until revocation remains unaffected. You can also prevent the storage of cookies from the outset by configuring your browser software accordingly. However, if you configure your browser to reject all cookies, this may limit the functionality of this and other websites. Additionally, you can prevent Google from collecting and processing the data generated by the cookie related to your use of the website (including your IP address) by downloading and installing the Google Analytics Opt-out Browser Add-on available <a href="https://tools.google.com/dlpage/gaoptout">HERE</a>.</p>

<p>For more information on the terms of use of Google Analytics and privacy at Google, please visit <a href="https://marketingplatform.google.com/about/analytics/terms/en/">here</a> and <a href="https://policies.google.com/?hl=en">here</a>.</p>

        <!---<iframe src='https://widgets.sociablekit.com/instagram-feed/iframe/246755' frameborder='0' width='100%' height='1000'></iframe>-->
    </div>
</template>
  
  <script>
  
  export default {
    name: 'PrivacyView',
    components: {
    },
    data(){
      return{
      }
    },
    methods: {
    }
  
  }
  </script>
  
  <style scoped>
    .outerContainer{
      padding: 40px 80px;
      color: white;
      text-align: left;
    }

    h1{
      color: white;
    font-size: 12vw;
    letter-spacing: 0.1em;
    font-weight: 500;
    }

    h2{
      font-size: 30px;
      padding: 20px;
    }

    h3{
      font-weight: bold;
    }

    iframe{
        margin: 100px auto;
    max-width: 800px;
    }
  </style>
  
  
  
